const pythonQuestions = [
  { word: "python", hint: "High-level programming language" },
  { word: "print", hint: "Function to display output" },
  { word: "pep8", hint: "Style guide for Python code" },
  { word: "variable", hint: "Container for storing data" },
  { word: "comment", hint: "Explanatory note in code" },
  { word: "list", hint: "Ordered collection of items" },
  { word: "function", hint: "Reusable block of code" },
  { word: "tuple", hint: "Immutable ordered sequence" },
  { word: "class", hint: "Blueprint for creating objects" },
  { word: "if", hint: "Conditional statement" },
  { word: "while", hint: "Looping structure" },
  { word: "dictionary", hint: "Key-value pairs collection" },
  { word: "module", hint: "Python file with code" },
  { word: "package", hint: "Group of Python modules" },
  { word: "exception", hint: "Error handling in Python" },
  { word: "lambda", hint: "Anonymous function" },
  { word: "file", hint: "Data storage in Python" },
  { word: "decorator", hint: "Modify function behavior" },
  { word: "listcomprehension", hint: "Concise list creation" },
  { word: "recursion", hint: "Function calling itself" },
  { word: "iterator", hint: "Object that can be iterated" },
  { word: "generator", hint: "Function that yields values" },
  { word: "oop", hint: "Object-Oriented Programming" },
  { word: "inheritance", hint: "Acquiring properties from a parent class" },
  { word: "polymorphism", hint: "One interface, many forms" },
  { word: "encapsulation", hint: "Bundling data and methods" },
  { word: "abstraction", hint: "Hiding complex implementation details" },
  { word: "slice", hint: "Extracting parts of a sequence" },
  { word: "map", hint: "Apply a function to all items in an iterable" },
  { word: "filter", hint: "Select items from an iterable based on a condition" },
  { word: "reduce", hint: "Aggregate items in an iterable to a single value" },
  { word: "set", hint: "Unordered collection of unique items" },
  { word: "exceptionhandling", hint: "Dealing with errors in code" },
  { word: "globalvariable", hint: "Variable accessible throughout the code" },
  { word: "localvariable", hint: "Variable with limited scope" },
  { word: "typeconversion", hint: "Changing the data type of a value" },
  { word: "json", hint: "Data interchange format" },
  { word: "csv", hint: "Comma-Separated Values" },
  { word: "pandas", hint: "Data manipulation library" },
  { word: "numpy", hint: "Numerical computing library" },
  { word: "virtualenvironment", hint: "Isolated Python environment" },
  { word: "assertions", hint: "Check if a statement is true" },
  { word: "asynchronous", hint: "Concurrent execution of tasks" },
  { word: "jsonparsing", hint: "Reading and writing JSON data" },
  { word: "webscraping", hint: "Extracting data from websites" },
  { word: "api", hint: "Application Programming Interface" },
  { word: "restfulapi", hint: "Representational State Transfer API" },
  { word: "httpmethods", hint: "GET, POST, PUT, DELETE" },
  { word: "database", hint: "Structured collection of data" },
  { word: "sql", hint: "Structured Query Language" },
  { word: "orm", hint: "Object-Relational Mapping" },
  { word: "flask", hint: "Web framework for Python" },
  { word: "django", hint: "High-level Python web framework" },
  { word: "tuplesvslists", hint: "Immutable vs Mutable sequences" },
  { word: "memorymanagement", hint: "How Python manages memory" },
  { word: "shallowvsdeepcopy", hint: "Copying objects in Python" },
  { word: "ducktyping", hint: "Behavior over explicit type" },
  { word: "bigonotation", hint: "Algorithm efficiency" },
  { word: "lambdavsdef", hint: "Anonymous functions vs named functions" },
  { word: "generatorsvslists", hint: "Lazy evaluation vs eager evaluation" },
  { word: "pythoniccode", hint: "Writing code the Python way" },
  { word: "pep", hint: "Python Enhancement Proposal" },
  { word: "jupyternotebook", hint: "Interactive computing environment" },
  { word: "pip", hint: "Package installer for Python" },
  { word: "anaconda", hint: "Distribution of Python for data science" },
  { word: "pytest", hint: "Testing framework for Python" },
  { word: "git", hint: "Version control system" },
  { word: "github", hint: "Web-based hosting service for Git repositories" },
  { word: "docker", hint: "Containerization platform" },
  { word: "agile", hint: "Project management methodology" },
  { word: "scrum", hint: "Framework for agile project management" },
  { word: "kotlin", hint: "Programming language for the JVM" },
  { word: "machinelearning", hint: "AI technique for systems to learn from data" },
  { word: "deeplearning", hint: "Neural networks with multiple layers" },
  { word: "datascience", hint: "Extracting insights from data" },
  { word: "artificialintelligence", hint: "Simulating human intelligence in machines" },
  { word: "cybersecurity", hint: "Protecting systems, networks, and programs" },
  { word: "blockchain", hint: "Distributed ledger technology" },
  { word: "iot", hint: "Internet of Things" },
  { word: "cloudcomputing", hint: "On-demand delivery of computing services" },
  { word: "devops", hint: "Collaboration between development and operations" },
  { word: "linux", hint: "Open-source operating system" },
  { word: "opensource", hint: "Software with a license for public use and modification" },
  { word: "webdevelopment", hint: "Building websites and web applications" },
  { word: "mobiledevelopment", hint: "Creating applications for mobile devices" },
  { word: "datavisualization", hint: "Presenting data graphically" },
  { word: "uiuxdesign", hint: "User interface and user experience design" },
  { word: "cybersecurity", hint: "Protecting systems, networks, and programs" },
  { word: "blockchain", hint: "Distributed ledger technology" },
  { word: "iot", hint: "Internet of Things" },
  { word: "cloudcomputing", hint: "On-demand delivery of computing services" },
  { word: "devops", hint: "Collaboration between development and operations" },
  { word: "linux", hint: "Open-source operating system" },
  { word: "opensource", hint: "Software with a license for public use and modification" },
  { word: "webdevelopment", hint: "Building websites and web applications" },
  { word: "mobiledevelopment", hint: "Creating applications for mobile devices" },
  { word: "datavisualization", hint: "Presenting data graphically" },
  { word: "uiuxdesign", hint: "User interface and user experience design" },
];
